# Telegram setup
TELEGRAM_TOKEN = '<YOUR_TELEGRAM_BOT_TOKEN>'
TELEGRAM_CHANNEL_ID = '<YOUR_TELEGRAM_CHANNEL_ID>'


# Twitter setup
TWITTER_API_KEY = '<YOUR_TWITTER_API_KEY>'
TWITTER_API_SECRET_KEY = '<YOUR_TWITTER_API_SECRET_KEY>'
TWITTER_ACCESS_TOKEN = '<YOUR_TWITTER_ACCESS_TOKEN>'
TWITTER_ACCESS_TOKEN_SECRET = '<YOUR_TWITTER_ACCESS_TOKEN_SECRET>'

